# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8adf50f1-cfa0-4d7f-94a9-09a0b1b0419a";
      fsType = "ext4";
    };

  fileSystems."/storage" =
    { device = "icarus.internal:/zbackup";
      fsType = "nfs";
    };
  systemd.targets.nfs-client.requiredBy = [ "storage.mount" ];
  systemd.targets.nfs-client.before = [ "storage.mount" ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ca217d6-538e-4919-a57f-c5cbaeb93832"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
