[[servers]]
  host = "ldap.internal"
  port = 389
  search_filter = "(uid=%s)"
  search_base_dns = ["ou=accounts,o=redbrick"]
  group_search_base_dns = ["ou=groups,o=redbrick"]
[servers.attributes]
  name = "cn"
  username = "uid"
  member_of = "objectClass"
  email =  "altmail"
[[servers.group_mappings]]
  group_dn = "cn=root"
  org_role = "Admin"
  grafana_admin = true # Available in Grafana v5.3 and above
[[servers.group_mappings]]
  group_dn = "cn=helpdesk"
  org_role = "Editor"
[[servers.group_mappings]]
  group_dn = "*"
  org_role = "Viewer"
