# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  common = import ../../common/variables.nix;
in {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "megaraid_sas" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zdaedalus/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zdaedalus/nix_store";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/624D-3268";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1634b3dd-b7e4-4017-8918-53ffb491120b"; }
    ];

  fileSystems."/gstorage/brick1/gvhomes" = common.zfsMountConfig "zbrick1/gvhomes";
  fileSystems."/gstorage/brick2/gvhomes" = common.zfsMountConfig "zbrick2/gvhomes";
  fileSystems."/gstorage/brick3/gvhomes" = common.zfsMountConfig "zbrick3/gvhomes";

  fileSystems."/gstorage/brick1/gvservices" = common.zfsMountConfig "zbrick1/gvservices";
  fileSystems."/gstorage/brick2/gvservices" = common.zfsMountConfig "zbrick2/gvservices";
  fileSystems."/gstorage/brick3/gvservices" = common.zfsMountConfig "zbrick3/gvservices";

  fileSystems."/gstorage/brick1/gvarchive" = common.zfsMountConfig "zbrick1/gvarchive";
  fileSystems."/gstorage/brick2/gvarchive" = common.zfsMountConfig "zbrick2/gvarchive";
  fileSystems."/gstorage/brick3/gvarchive" = common.zfsMountConfig "zbrick3/gvarchive";
}
