# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:
let
  common = import ../../common/variables.nix;
in {
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "megaraid_sas" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e14cbe8f-bfe0-4438-824c-4af8793a1d00";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2566bfc9-6da9-433e-afe8-ad07abf0e19a";
      fsType = "ext4";
    };

  fileSystems."/gstorage/brick1/gvhomes" = common.zfsMountConfig "zbrick1/gvhomes";
  fileSystems."/gstorage/brick2/gvhomes" = common.zfsMountConfig "zbrick2/gvhomes";
  fileSystems."/gstorage/brick3/gvhomes" = common.zfsMountConfig "zbrick3/gvhomes";

  fileSystems."/gstorage/brick1/gvservices" = common.zfsMountConfig "zbrick1/gvservices";
  fileSystems."/gstorage/brick2/gvservices" = common.zfsMountConfig "zbrick2/gvservices";
  fileSystems."/gstorage/brick3/gvservices" = common.zfsMountConfig "zbrick3/gvservices";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e915505b-9777-4362-ab8e-0b6d069e3916"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
